### PR TITLE
Fix workflows: fix setup, default branch, and checkout

### PR DESCRIPTION
**Pull request by dsayling**
While I was waiting for my other PR I noticed the recent move to gh actions occurred. 

1. The default branch here is still `master` and not `main`.
2. use the poetry install to setup the environment instead of the env setup script via the bootstrap.sh
3. `fetch-depth: 0` provides a full checkout including tags.

I also removed the caching per jolly-good-toolbelt/jgt_tools/pull/44 as well

### CODE REVIEW

**Review by brolewis — APPROVED** [review]
This is what I get for stealing workflows from another project. Thanks.

**Comment by dsayling** [comment]
Would you like me to fix the rest of the workflow here?

**Comment by brolewis** [comment]
@dsayling Sure thing. I know that https://github.com/jolly-good-toolbelt/sphinx_gherkindoc/blob/master/.github/workflows/pull-requests.yml#L32 should be `run: bash bootstrap.sh` but then the version checker will fail because we don't get a full clone from the checkout action, so need to figure out an option there. If you do, awesome, but if not, don't stress about that step.

**Review by sdutton-personal — APPROVED** [review]
LGTM

**Comment by dsayling** [comment]
Not a problem at all. Happy to contribute.

**Comment by brolewis** [comment]
@dsayling You mind converting to a draft while you add changes? Don't want anyone not paying *too* close attention to merge while you're working :)

**Comment by dsayling** [comment]
@brolewis @dgou - ready for review

**Comment by dsayling** [comment]
As an aside, I'm wondering if the PR workflow should also attempt to build the docs to ensure the post merge action runs successfully.

**Review by dgou — APPROVED** [review]
LGTM, didn't see anything objectionable, but also have not pulled to run it.
Will do that asynchronously.

**Comment by dgou** [comment]
Pulled the PR and did the triumverate of `bootstrap`, `self-check` and `run-tests` and that all passed.

**Pull request merged**
